version: '3.8'

services:
  # Git watcher service
  git-watcher:
    image: alpine/git:latest
    container_name: cv-platform-git-watcher
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: >
      sh -c "
        apk add --no-cache docker-cli &&
        while true; do
          echo '[Git Watcher] Checking for updates...'
          git fetch origin
          LOCAL=$$(git rev-parse HEAD)
          REMOTE=$$(git rev-parse origin/main)
          if [ \"$$LOCAL\" != \"$$REMOTE\" ]; then
            echo '[Git Watcher] New changes detected, updating...'
            git pull origin main
            echo '[Git Watcher] Restarting services...'
            docker-compose -f docker-compose.yml restart backend frontend
            echo '[Git Watcher] Services restarted'
          fi
          sleep 30
        done
      "
    restart: unless-stopped
    depends_on:
      - backend
      - frontend

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cv-platform-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    command: python app/main_simple.py
    restart: unless-stopped

  # Frontend service  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: cv-platform-frontend
    ports:
      - "5174:5174"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm run dev -- --host 0.0.0.0
    restart: unless-stopped